# Generated by Django 4.1.7 on 2023-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="walletAddress",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
