# Generated by Django 4.1.7 on 2023-06-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_order_walletaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="walletAddress",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
