# Generated by Django 4.1.7 on 2023-06-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_shippingaddress_walletaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="isTokenize",
            field=models.BooleanField(default=False),
        ),
    ]
